### PR TITLE
Static

### PR DESCRIPTION
**Pull request by timthelion**
This fixes @tmszi 's and @PetrKudy 's mass communications branch to allow deployment to heroku.

### CODE REVIEW

**Comment by timthelion** [comment]
The key change here, is adding the 

`python manage.py build_contenttools`

command to the post_compile hook which is run by heroku's buildpack

as well as reseting the `STATICFILES_STORAGE = 'project.settings.custom_storage.CustomStaticFilesStorage'` variable in the heroku.py settings file after it is over-ridden by heroku built in settings.

**Comment by timthelion** [comment]
@PetrKudy ťuk ťuk

**Comment by PetrKudy** [comment]
No heroku to je nasazené. 
Čekáme teď na Ondru až to otestuje :-)

**Comment by tmszi** [comment]
Hello Timothy, Petr,

I updated the original PR #134, solves minor bugs and deploy on Heroku. I checked the deployed tested version (link from Ondřej). It is not published correctly. Could you update that deployed branch code please?

Default behavior (ContentTools editor on tested Heroku server):

contenttools_editor_def

Expected behavior:

contenttools_editor_exp

**Comment by timthelion** [comment]
Can you please try to merge in the changes in this branch into your branch? It seems you are missing most of my changes. Your branch doesn't deploy at all:

````
remote:        Your Pipfile.lock (341212) is out of date. Expected: (4dcf23).
remote:        Aborting deploy.
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
````

**Comment by tmszi** [comment]
> Can you please try to merge in the changes in this branch into your branch? It seems you are missing most of my changes. Your branch doesn't deploy at all:
> 
> ```
> remote:        Your Pipfile.lock (341212) is out of date. Expected: (4dcf23).
> remote:        Aborting deploy.
> remote:  !     Push rejected, failed to compile Python app.
> remote: 
> remote:  !     Push failed
> ```

Yes of course. I've incorporated your changes.

**Comment by PetrKudy** [comment]
in https://github.com/auto-mat/klub/pull/134 already

**Pull request closed without merging**
